// Shared config + Supabase client factories for the e2e test-user scripts.
//
// These scripts run as `node --env-file=.env.local scripts/test-user/<x>.mjs`
// from `apps/web` so they pick up the same Supabase project + keys the app
// uses. NEVER call from inside the app — the service-role key bypasses RLS
// and these helpers leak password material.
//
// See docs/operations/e2e-test-user.md for the full runbook.

import { readFileSync, writeFileSync, renameSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomBytes } from 'node:crypto'

import { createClient } from '@supabase/supabase-js'
import { createServerClient } from '@supabase/ssr'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/** Repo-relative path: `apps/web/.test-user.local.json` (gitignored). */
export const TEST_USER_FILE = resolve(__dirname, '../../.test-user.local.json')

/** Repo-relative path: `apps/web/.test-cookies.txt` (gitignored). */
export const COOKIES_FILE = resolve(__dirname, '../../.test-cookies.txt')

/**
 * Stable test-user email. `.local` is reserved by RFC 6762 (mDNS) so this
 * domain will never resolve — no chance of accidentally emailing a real user.
 */
export const TEST_USER_EMAIL = process.env.E2E_TEST_USER_EMAIL ?? 'billing-e2e@speclyy.local'

function requireEnv(name) {
  const value = process.env[name]
  if (!value) {
    console.error(`✗ ${name} not set. Run with --env-file=.env.local from apps/web.`)
    process.exit(1)
  }
  return value
}

export function getEnv() {
  return {
    SUPABASE_URL: requireEnv('NEXT_PUBLIC_SUPABASE_URL'),
    SUPABASE_PUBLISHABLE_KEY: requireEnv('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY'),
    SUPABASE_SECRET_KEY: requireEnv('SUPABASE_SECRET_KEY'),
  }
}

/**
 * Service-role client for admin operations (create user, reset state).
 * Bypasses RLS — never use this client to drive end-user-equivalent flows.
 */
export function getAdminClient() {
  const { SUPABASE_URL, SUPABASE_SECRET_KEY } = getEnv()
  return createClient(SUPABASE_URL, SUPABASE_SECRET_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
}

/**
 * SSR-style server client that captures cookie writes into the provided
 * array. Pass to `auth.signInWithPassword(...)` and the cookies the app
 * would set on the response are appended to `writes` instead — letting us
 * dump them to disk in the exact format @supabase/ssr expects to read back.
 */
export function getCaptureClient(writes) {
  const { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } = getEnv()
  return createServerClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    cookies: {
      getAll: () => [],
      setAll: (cookiesToSet) => writes.push(...cookiesToSet),
    },
  })
}

/** Idempotent JSON read. Returns null if the file doesn't exist. */
export function readTestUser() {
  if (!existsSync(TEST_USER_FILE)) return null
  return JSON.parse(readFileSync(TEST_USER_FILE, 'utf8'))
}

/** Atomic-ish write — write to tmp + rename so a Ctrl-C can't half-write. */
export function writeTestUser(data) {
  mkdirSync(dirname(TEST_USER_FILE), { recursive: true })
  const tmp = `${TEST_USER_FILE}.tmp`
  writeFileSync(tmp, JSON.stringify(data, null, 2) + '\n', { mode: 0o600 })
  renameSync(tmp, TEST_USER_FILE)
}

/**
 * 24 alphanumeric chars — enough entropy that brute-forcing is not viable
 * even against the publishable key, while keeping it readable when the user
 * eyeballs the file.
 */
export function generatePassword() {
  return randomBytes(18).toString('base64url')
}

/**
 * Convert the cookies @supabase/ssr would set on a response into Netscape
 * cookies.txt format that `curl -b cookies.txt` understands.
 *
 * Format:  domain  TAILMATCH-flag  path  secure  expiration  name  value
 * (tab-separated). The 2nd column is `TRUE` if the cookie is sent for
 * subdomains of `domain`, `FALSE` for exact-host match. Curl matches the
 * Host header literally, so a cookie scoped to `localhost` is NOT sent
 * to `127.0.0.1` and vice versa — we emit one row per host the dev server
 * commonly answers on, so `curl -b` works regardless of which the user
 * types. Override the host list with `E2E_COOKIE_HOSTS=foo,bar` if you've
 * bound dev to something custom.
 */
export function toNetscapeCookies(writes, hosts = ['localhost', '127.0.0.1']) {
  const hostList = process.env.E2E_COOKIE_HOSTS
    ? process.env.E2E_COOKIE_HOSTS.split(',').map((h) => h.trim()).filter(Boolean)
    : hosts
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by scripts/test-user/login.mjs',
    `# Hosts: ${hostList.join(', ')} (override via E2E_COOKIE_HOSTS=…)`,
  ]
  for (const { name, value, options } of writes) {
    const path = options?.path ?? '/'
    const secure = 'FALSE' // localhost dev — never secure
    // Use 1-year expiry by default; @supabase/ssr's `maxAge` is seconds.
    const maxAge = options?.maxAge ?? 60 * 60 * 24 * 365
    const expiry = Math.floor(Date.now() / 1000) + maxAge
    // curl wants the literal value; @supabase/ssr sets it pre-encoded.
    // Emit one row per host so either `localhost` or `127.0.0.1` works.
    // The `#HttpOnly_` prefix is curl's convention for HttpOnly cookies
    // (purely cosmetic — curl still sends them on every matching request).
    for (const host of hostList) {
      lines.push(
        ['#HttpOnly_' + host, 'FALSE', path, secure, String(expiry), name, value].join('\t'),
      )
    }
  }
  return lines.join('\n') + '\n'
}
