import type { DemoProject } from './types'

// Four canonical project archetypes for the launch markets — used as sample
// content on the Projects hub and to populate the "Your projects" demo state.
// The fields here are the Hub-relevant subset of the full schema; group/item
// detail uses a separate module.
export const DEMO_PROJECTS: readonly DemoProject[] = [
  {
    id: 'atherton',
    name: 'Atherton Residence',
    type: 'Residential — New build',
    typeKey: 'new-build',
    location: 'Atherton, CA',
    client: 'Henley & Co.',
    market: 'Los Angeles',
    phase: 'Specification',
    status: 'Active',
    statusKind: 'neutral',
    progress: 0.42,
    groups: 8,
    items: 147,
    updated: '2h ago',
    palette: ['#C7B8A1', '#8C7A63', '#3F352B', '#E8DFCE'],
    accent: '#C06B3E',
  },
  {
    id: 'laurel',
    name: 'Laurel Canyon Renovation',
    type: 'Residential — Renovation',
    typeKey: 'reno',
    location: 'Los Angeles, CA',
    client: 'Private',
    market: 'Los Angeles',
    phase: 'Procurement',
    status: 'Active',
    statusKind: 'neutral',
    progress: 0.71,
    groups: 12,
    items: 284,
    updated: 'Yesterday',
    palette: ['#A89884', '#6E5A48', '#2A2118', '#D4C5AE'],
    accent: '#A3552B',
  },
  {
    id: 'merit',
    name: 'Merit & Co. Lobby',
    type: 'Commercial — Hospitality',
    typeKey: 'commercial',
    location: 'Dallas, TX',
    client: 'Bennett Group',
    market: 'Dallas',
    phase: 'Concept',
    status: 'Active',
    statusKind: 'neutral',
    progress: 0.18,
    groups: 5,
    items: 62,
    updated: '4d ago',
    palette: ['#6B4A2C', '#2B1F14', '#A98861', '#0D0B08'],
    accent: '#7E4020',
  },
  {
    id: 'staging',
    name: 'Calgary Show Suite',
    type: 'Staging — Model home',
    typeKey: 'staging',
    location: 'Calgary, AB',
    client: 'Westfield Homes',
    market: 'Calgary',
    phase: 'Install ready',
    status: 'Final',
    statusKind: 'complete',
    progress: 1.0,
    groups: 6,
    items: 94,
    updated: 'Last week',
    palette: ['#E8DFCE', '#B49E84', '#5C4B38', '#F5EFE3'],
    accent: '#6E8A5C',
  },
]
